#!/usr/bin/env python3
"""Run a bounded larger-sample GNM comparison when the external environment exists."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_EXTERNAL_PYTHON = Path("/home/nico/src/GNM/gnm/shape/.venv/bin/python")
COMPARATOR = ROOT / "tools" / "gnm" / "compare_gnm_quality_scales.py"
BUILDER = ROOT / "tools" / "gnm" / "build_runtime_pack.py"
CANONICAL_PACK = ROOT / "tools" / "gnm" / "work" / "gnm-morphology-pack.json"
CANONICAL_LANDMARKS = ROOT / "tools" / "gnm" / "work" / "gnm-landmarks.json"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=400, choices=(400, 800))
    parser.add_argument("--seed", type=int, default=400)
    parser.add_argument("--sigma", type=float, default=1.15)
    parser.add_argument("--families", type=int, default=8)
    parser.add_argument("--python", type=Path, help="external GNM Python; defaults to GNM_PYTHON or the documented local path")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args(argv)


def external_python(args: argparse.Namespace) -> Path:
    return Path(args.python or os.environ.get("GNM_PYTHON", DEFAULT_EXTERNAL_PYTHON))


def availability(python: Path) -> tuple[bool, str]:
    if not python.is_file():
        return False, f"external GNM Python is missing: {python}"
    probe = subprocess.run(
        [str(python), "-c", "import numpy; from gnm.shape import gnm_numpy"],
        capture_output=True,
        text=True,
        check=False,
    )
    if probe.returncode:
        detail = (probe.stderr or probe.stdout).strip().splitlines()
        suffix = f": {detail[-1]}" if detail else ""
        return False, f"external GNM/NumPy imports are unavailable in {python}{suffix}"
    return True, ""


def build_command(python: Path, count: int, seed: int, sigma: float, families: int, work_dir: Path, output: Path) -> list[str]:
    return [
        str(python), str(BUILDER),
        "--count", str(count), "--seed", str(seed), "--sigma", str(sigma),
        "--families", str(families), "--work-dir", str(work_dir), "--output", str(output),
    ]


def comparison_command(
    candidate_pack: Path,
    candidate_landmarks: Path,
    rerun_pack: Path,
    rerun_landmarks: Path,
    output: Path,
    count: int,
) -> list[str]:
    return [
        sys.executable, str(COMPARATOR),
        "--candidate-pack", str(candidate_pack),
        "--candidate-landmarks", str(candidate_landmarks),
        "--rerun-candidate-pack", str(rerun_pack),
        "--rerun-candidate-landmarks", str(rerun_landmarks),
        "--canonical-pack", str(CANONICAL_PACK),
        "--canonical-landmarks", str(CANONICAL_LANDMARKS),
        "--count", str(count), "--output", str(output),
    ]


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    python = external_python(args)
    available, reason = availability(python)
    if args.dry_run:
        print(f"External Python: {python}")
        print(f"Available: {available}")
        if reason:
            print(f"Reason: {reason}")
        print("No files are generated by --dry-run.")
        return 0

    if not available:
        command = [
            sys.executable, str(COMPARATOR),
            "--candidate-pack", str(ROOT / "tools/gnm/work" / f"gnm-morphology-pack-{args.count}.json"),
            "--canonical-pack", str(CANONICAL_PACK),
            "--canonical-landmarks", str(CANONICAL_LANDMARKS),
            "--count", str(args.count), "--unavailable-reason", reason,
            "--output", str(args.output),
        ]
        subprocess.run(command, cwd=ROOT, check=True)
        return 0

    with tempfile.TemporaryDirectory(prefix=f"gnm-scale-{args.count}-") as directory:
        root = Path(directory)
        first_work = root / "run-a"
        second_work = root / "run-b"
        first_pack = first_work / f"gnm-morphology-pack-{args.count}.json"
        second_pack = second_work / f"gnm-morphology-pack-{args.count}.json"
        for command in (
            build_command(python, args.count, args.seed, args.sigma, args.families, first_work, first_pack),
            build_command(python, args.count, args.seed, args.sigma, args.families, second_work, second_pack),
        ):
            subprocess.run(command, cwd=ROOT, check=True)
        command = comparison_command(
            first_pack,
            first_work / f"gnm-landmarks-{args.count}.json",
            second_pack,
            second_work / f"gnm-landmarks-{args.count}.json",
            args.output,
            args.count,
        )
        subprocess.run(command, cwd=ROOT, check=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
